name: Multi-job-pipeline

on: push


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
        
      - name: checkout git repo
        uses: actions/checkout@v4
      - name: download files using wget
        run: |
            wget https://www.datablist.com/customers-100.csv
            cat customers-100.csv
        


