name: Multi-job-pipeline

on: push


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
        
      - name: checkout git repo
        uses: actions/checkout@v4
      - name: download files using wget
        run: |
            wget https://raw.githubusercontent.com/datablist/sample-csv-files/main/files/customers/customers-100.csv
            cat customers-100.csv
        


